package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customerDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Unique Id")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label(value = "Owner Type")
	private java.lang.String ownerType;
	@org.kie.api.definition.type.Label(value = "Annual Income")
	private java.lang.Long anuualIncome;
	@org.kie.api.definition.type.Label(value = "Years Of Stay")
	private java.lang.Integer yearsOfStay;
	@org.kie.api.definition.type.Label(value = "Email ID")
	private java.lang.String email;
	@org.kie.api.definition.type.Label(value = "Phone Number")
	private java.math.BigInteger phoneNumber;

	public customerDetails() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getOwnerType() {
		return this.ownerType;
	}

	public void setOwnerType(java.lang.String ownerType) {
		this.ownerType = ownerType;
	}

	public java.lang.Long getAnuualIncome() {
		return this.anuualIncome;
	}

	public void setAnuualIncome(java.lang.Long anuualIncome) {
		this.anuualIncome = anuualIncome;
	}

	public java.lang.Integer getYearsOfStay() {
		return this.yearsOfStay;
	}

	public void setYearsOfStay(java.lang.Integer yearsOfStay) {
		this.yearsOfStay = yearsOfStay;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.math.BigInteger getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.math.BigInteger phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public customerDetails(java.lang.String name, java.lang.Integer id,
			java.lang.String ownerType, java.lang.Long anuualIncome,
			java.lang.Integer yearsOfStay, java.lang.String email,
			java.math.BigInteger phoneNumber) {
		this.name = name;
		this.id = id;
		this.ownerType = ownerType;
		this.anuualIncome = anuualIncome;
		this.yearsOfStay = yearsOfStay;
		this.email = email;
		this.phoneNumber = phoneNumber;
	}

}